# Generated by Django 5.1.6 on 2025-03-13 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrador',
            name='bloqueado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='director',
            name='bloqueado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profesor',
            name='bloqueado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='administrador',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='administrador',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='director',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='director',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
