# Generated by Django 5.1.6 on 2025-02-26 19:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_acceso_aula_estudiante'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('crear', 'Crear'), ('editar', 'Editar'), ('eliminar', 'Eliminar'), ('login', 'Inicio de sesión')], max_length=20)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.DeleteModel(
            name='Acceso',
        ),
        migrations.AddField(
            model_name='administrador',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='aula',
            name='profesor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aula_asignada', to='app1.profesor'),
        ),
        migrations.AddField(
            model_name='director',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='fecha_inscripcion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='profesor',
            name='especialidad',
            field=models.CharField(choices=[('Educación Infantil', 'Educación Infantil'), ('Educación Primaria', 'Educación Primaria')], default='Educación Primaria', max_length=50),
        ),
        migrations.AddField(
            model_name='profesor',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='aula',
            name='capacidad',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='aula',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudiantes', to='app1.aula'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='edad',
            field=models.PositiveIntegerField(),
        ),
    ]
