# Generated by Django 5.1.6 on 2025-03-14 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_formulario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formulario',
            old_name='despcricion',
            new_name='descripcion',
        ),
    ]
