# Generated by Django 5.1.6 on 2025-02-27 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_actividad_delete_acceso_administrador_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grado', models.CharField(max_length=50)),
                ('numero_estudiantes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Actividad',
        ),
        migrations.RemoveField(
            model_name='administrador',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='director',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='fecha_inscripcion',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='fecha_creacion',
        ),
        migrations.AlterField(
            model_name='aula',
            name='nivel',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='aula',
            name='profesor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aulas', to='app1.profesor'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='nivel',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='especialidad',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='clase',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clases', to='app1.profesor'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='profesor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='app1.profesor'),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='clase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='app1.clase'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='evaluacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='app1.evaluacion'),
        ),
    ]
