# Generated by Django 5.1.6 on 2025-03-07 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_clase_comentario_evaluacion_evento_delete_actividad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clase',
            name='grado',
        ),
        migrations.RemoveField(
            model_name='clase',
            name='numero_estudiantes',
        ),
        migrations.RemoveField(
            model_name='evaluacion',
            name='clase',
        ),
        migrations.AddField(
            model_name='clase',
            name='aula',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clases', to='app1.aula'),
        ),
        migrations.AddField(
            model_name='clase',
            name='estudiantes',
            field=models.ManyToManyField(related_name='clases', to='app1.estudiante'),
        ),
        migrations.AddField(
            model_name='clase',
            name='nombre',
            field=models.CharField(default='Clase sin nombre', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='aula',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='app1.aula'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clase',
            name='profesor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clases', to='app1.profesor'),
        ),
    ]
